
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'demo_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_demo_nanw'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  current_champion: Lakers


on-run-start: "{{ insert_audits('run_start') }}"
on-run-end: "{{ insert_audits('run_end') }}"

# on-run-start: "insert into DEMO_DB.PUBLIC.DBT_AUDITS (audit_type) values('run_start');commit;"
# on-run-end: "insert into DEMO_DB.PUBLIC.DBT_AUDITS (audit_type) values('run_end');commit;"


models:
  # pre-hook: "insert into DEMO_DB.PUBLIC.DBT_AUDITS (audit_type) values('model_start');commit;"
  # post-hook: "insert into DEMO_DB.PUBLIC.DBT_AUDITS (audit_type) values('model_end');commit;"

  pre-hook: "{{ insert_audits('model_start') }}"
  post-hook: "{{ insert_audits('model_end') }}"

  demo_dbt:
      # Applies to all files under models/staging/
      staging:
          +materialized: view
          +schema: staging
          example:
            +materialized: table


