
version: 2

models:
    - name: example_my_first_dbt_model
      description: '{{ doc("table_events") }}'
      columns:
          - name: id
            description: '{{ doc("first_dbt_model_primary_key") }}'
            tests:
                - unique
                - not_null

    - name: example_my_second_dbt_model
      description: "A starter dbt model, this is the second table"
      columns:
          - name: id
            description: '{{ doc("secound_dbt_model_primary_key") }}'
            tests:
                - unique
                - not_null
    