
version: 2

models:
    - name: example_my_first_dbt_model
      description: "A starter dbt model, this is the first table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: example_my_second_dbt_model
      description: "A starter dbt model, this is the second table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
